services:
  db:
    image: postgres:15
    container_name: itami-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itami
    ports:
      - "5433:5432"
    volumes:
      - itami_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: itami-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  itami_pgdata:
